import type { Locale } from "./routes";
export const solutionRoutes = [
  "siti-web",
  "restyling-siti-web",
  "sviluppo-web",
  "seo-performance",
  "siti-multilingua",
  "assistenza-web",
] as const;
const it = [
  [
    "Siti web vetrina",
    "Un sito che spiega chi sei. E perché sceglierti.",
    "Per professionisti, studi e piccole imprese che vogliono presentarsi con chiarezza e trasformare una visita in una conversazione.",
    "Partiamo dalle domande dei tuoi clienti: cosa fai, a chi ti rivolgi e come possono contattarti. Costruiamo le pagine attorno a queste risposte, con una grafica riconoscibile e un percorso semplice anche dal telefono.",
    [
      "Architettura delle pagine e priorità dei contenuti",
      "Presentazione di attività, servizi e punti di forza",
      "Contatti, indicazioni e richieste di preventivo",
      "Layout curato per telefono, tablet e computer",
    ],
    "Il risultato è una presenza online che puoi condividere con sicurezza: nelle ricerche, sui social, nella firma email e durante un incontro.",
    "design",
  ],
  [
    "Restyling siti web",
    "Il tuo lavoro è cresciuto. Il tuo sito lo racconta?",
    "Rinnoviamo un sito datato, confuso o poco comodo sul cellulare, conservando ciò che ha già valore.",
    "Prima di cambiare aspetto, analizziamo pagine, contenuti e percorsi. Individuiamo gli ostacoli: testi difficili da leggere, contatti poco visibili, immagini pesanti o una navigazione dispersiva. Poi definiamo le priorità del nuovo sito.",
    [
      "Inventario delle pagine e degli indirizzi esistenti",
      "Nuova gerarchia visiva e testi più leggibili",
      "Revisione di menu, moduli e inviti al contatto",
      "Verifica degli URL e dei collegamenti nella migrazione",
    ],
    "Un restyling non deve cancellare la tua storia: le pagine utili e gli indirizzi indicizzati entrano nel piano di migrazione.",
    "analisi",
  ],
  [
    "Sviluppo web su misura",
    "Quando una pagina non basta, costruiamo la funzione.",
    "Soluzioni per richieste specifiche: moduli articolati, integrazioni e percorsi digitali pensati per la tua attività.",
    "Descriviamo insieme il processo da semplificare, gli utenti coinvolti e le informazioni da gestire. Il progetto nasce da un perimetro chiaro, prima di scegliere le tecnologie o stimare il lavoro.",
    [
      "Analisi dei requisiti e dei flussi di utilizzo",
      "Interfacce React e Next.js quando adatte al progetto",
      "Integrazioni con servizi e sistemi concordati",
      "Verifica dei percorsi principali e consegna documentata",
    ],
    "Funzionalità, integrazioni e manutenzione vengono definite nel preventivo: sai cosa comprende il progetto e cosa può essere sviluppato in una fase successiva.",
    "sviluppo",
  ],
  [
    "SEO e performance",
    "Fatti capire dalle persone. E dai motori di ricerca.",
    "Una base tecnica ordinata, pagine chiare e immagini leggere aiutano il tuo sito a essere consultato e scoperto.",
    "Lavoriamo su struttura, titoli, descrizioni e collegamenti interni. Verifichiamo l’esperienza da mobile e il peso delle risorse, senza promettere posizioni garantite nei risultati di ricerca.",
    [
      "Titoli e descrizioni coerenti con ogni pagina",
      "Sitemap, canonical e struttura degli indirizzi",
      "Ottimizzazione delle immagini e del caricamento",
      "Controllo dei contenuti e dei collegamenti principali",
    ],
    "Il posizionamento dipende anche da concorrenza, contenuti e continuità. Il primo passo è un sito tecnicamente curato e utile per chi lo visita.",
    "struttura",
  ],
  [
    "Siti multilingua",
    "La stessa identità, in più lingue.",
    "Presenta i tuoi servizi a chi arriva dall’estero, con pagine dedicate e una navigazione comprensibile.",
    "Ogni lingua ha il proprio percorso. Il visitatore può passare alla stessa pagina nella lingua desiderata, senza perdere il contesto; testi e lunghezze diverse vengono considerati nel layout.",
    [
      "Pagine e indirizzi dedicati per ogni lingua",
      "Selettore della lingua che conserva la pagina",
      "Metadati e collegamenti tra versioni linguistiche",
      "Revisione dei testi e delle traduzioni concordate",
    ],
    "Italiano e inglese sono un buon punto di partenza. Altre lingue e la revisione professionale delle traduzioni si definiscono in base al pubblico del progetto.",
    "design",
  ],
  [
    "Assistenza web",
    "Il sito continua a vivere dopo la pubblicazione.",
    "Aggiornamenti, nuovi contenuti e piccoli miglioramenti: un riferimento anche quando il progetto è online.",
    "Un nuovo servizio, un cambio di contatti o una pagina da aggiungere non devono diventare un problema. Concordiamo come gestire le richieste e quali attività includere nel supporto.",
    [
      "Aggiornamento di testi, immagini e informazioni",
      "Controllo dei moduli e dei collegamenti",
      "Manutenzione tecnica concordata",
      "Evoluzioni e nuove pagine su preventivo",
    ],
    "Durata, tempi di risposta e attività incluse sono indicati nell’accordo. Hosting, licenze e servizi esterni vengono valutati separatamente quando necessari.",
    "pubblicazione",
  ],
] as const;
const en = [
  [
    "Business websites",
    "A website that explains who you are. And why to choose you.",
    "For independent professionals, practices and small businesses who want to turn a visit into a conversation.",
    "We start with your customers’ questions: what you do, who you help and how to reach you. Those answers shape clear pages, a distinctive visual identity and a straightforward mobile experience.",
    [
      "Page architecture and content priorities",
      "Your business, services and strengths",
      "Contact details, directions and enquiry forms",
      "Layouts for phones, tablets and computers",
    ],
    "A presence you can confidently share in search, on social media, in your email signature and at your next meeting.",
    "design",
  ],
  [
    "Website redesign",
    "Your business has grown. Does your website show it?",
    "Refresh a dated or confusing website while preserving what already works.",
    "We review pages, content and visitor journeys before changing the design. Difficult text, hidden contact details, heavy images and confusing menus help us identify what to improve first.",
    [
      "Inventory of existing pages and URLs",
      "Clearer visual hierarchy and readable content",
      "Navigation, forms and contact journeys",
      "URL and link checks during migration",
    ],
    "A redesign should preserve your history. Useful pages and indexed addresses belong in the migration plan.",
    "analisi",
  ],
  [
    "Custom web development",
    "When a page is not enough, build the right feature.",
    "Tailored forms, integrations and digital journeys for the way your business works.",
    "We define the process to simplify, the people involved and the information to manage. A clear scope comes before technology choices and estimates.",
    [
      "Requirements and user journey analysis",
      "React and Next.js interfaces where appropriate",
      "Agreed third-party integrations",
      "Core journey testing and documented handover",
    ],
    "Features, integrations and maintenance are defined in the quote, so you know what is included and what can follow later.",
    "sviluppo",
  ],
  [
    "SEO and performance",
    "Clear for your visitors. Clear for search engines.",
    "An organised technical foundation, useful pages and lighter images make your website easier to explore.",
    "We work on structure, titles, descriptions and internal links. We review mobile usability and resource sizes without promising guaranteed search rankings.",
    [
      "Page-specific titles and descriptions",
      "Sitemap, canonical URLs and address structure",
      "Image and loading optimisation",
      "Content and key link checks",
    ],
    "Rankings also depend on competition, content and ongoing work. A useful, technically sound website is the starting point.",
    "struttura",
  ],
  [
    "Multilingual websites",
    "One identity. More languages.",
    "Introduce your services to international visitors through dedicated pages and clear navigation.",
    "Every language has its own journey. Visitors can switch to the equivalent page without losing context, while layouts account for different text lengths.",
    [
      "Dedicated pages and URLs for each language",
      "Language switching that preserves the page",
      "Language metadata and alternate links",
      "Agreed content and translation review",
    ],
    "Italian and English are a starting point. Further languages and professional translation review depend on your audience and project scope.",
    "design",
  ],
  [
    "Website support",
    "Your website keeps growing after launch.",
    "Updates, new content and practical improvements with an agreed point of contact.",
    "A new service, changed contact details or an additional page should be manageable. We agree how requests are handled and which activities belong in your support plan.",
    [
      "Text, image and business information updates",
      "Form and link checks",
      "Agreed technical maintenance",
      "New pages and features quoted separately",
    ],
    "Duration, response times and included tasks are set out in the agreement. Hosting, licences and external services are considered separately where needed.",
    "pubblicazione",
  ],
] as const;
export function solutions(locale: Locale) {
  return (locale === "it" ? it : en).map((s, i) => ({
    route: solutionRoutes[i],
    name: s[0],
    title: s[1],
    intro: s[2],
    body: s[3],
    features: s[4],
    outcome: s[5],
    image: s[6],
  }));
}
